
MSP_CRC_POLY = 0xD5

MSP_START = ord('$')
MSP_VERSION = {
    ord('M'): "V1",
    ord('X'): "V2",
}
MSP_TYPE = {
    ord('<'): "REQ",
    ord('>'): "RESP",
    ord('!'): "ERROR",
    ord('?'): "ELRS",
}

MSPv1_FUNC_TO_NAME = {
    1: "MSP_API_VERSION",
    2: "MSP_FC_VARIANT",
    3: "MSP_FC_VERSION",
    4: "MSP_BOARD_INFO",
    5: "MSP_BUILD_INFO",

    10: "MSP_NAME",
    11: "MSP_SET_NAME",

    32: "MSP_BATTERY_CONFIG",
    33: "MSP_SET_BATTERY_CONFIG",

    34: "MSP_MODE_RANGES",
    35: "MSP_SET_MODE_RANGE",

    36: "MSP_FEATURE_CONFIG",
    37: "MSP_SET_FEATURE_CONFIG",

    38: "MSP_BOARD_ALIGNMENT_CONFIG",
    39: "MSP_SET_BOARD_ALIGNMENT_CONFIG",

    40: "MSP_CURRENT_METER_CONFIG",
    41: "MSP_SET_CURRENT_METER_CONFIG",

    42: "MSP_MIXER_CONFIG",
    43: "MSP_SET_MIXER_CONFIG",

    44: "MSP_RX_CONFIG",
    45: "MSP_SET_RX_CONFIG",

    46: "MSP_LED_COLORS",
    47: "MSP_SET_LED_COLORS",

    48: "MSP_LED_STRIP_CONFIG",
    49: "MSP_SET_LED_STRIP_CONFIG",

    50: "MSP_RSSI_CONFIG",
    51: "MSP_SET_RSSI_CONFIG",

    52: "MSP_ADJUSTMENT_RANGES",
    53: "MSP_SET_ADJUSTMENT_RANGE",

    54: "MSP_CF_SERIAL_CONFIG",
    55: "MSP_SET_CF_SERIAL_CONFIG",

    56: "MSP_VOLTAGE_METER_CONFIG",
    57: "MSP_SET_VOLTAGE_METER_CONFIG",

    58: "MSP_SONAR_ALTITUDE",

    59: "MSP_PID_CONTROLLER",
    60: "MSP_SET_PID_CONTROLLER",

    61: "MSP_ARMING_CONFIG",
    62: "MSP_SET_ARMING_CONFIG",

    64: "MSP_RX_MAP",
    65: "MSP_SET_RX_MAP",

    66: "MSP_BF_CONFIG",
    67: "MSP_SET_BF_CONFIG",

    68: "MSP_REBOOT",

    69: "MSP_BF_BUILD_INFO",

    70: "MSP_DATAFLASH_SUMMARY",
    71: "MSP_DATAFLASH_READ",
    72: "MSP_DATAFLASH_ERASE",

    73: "MSP_LOOP_TIME",
    74: "MSP_SET_LOOP_TIME",

    75: "MSP_FAILSAFE_CONFIG",
    76: "MSP_SET_FAILSAFE_CONFIG",

    77: "MSP_RXFAIL_CONFIG",
    78: "MSP_SET_RXFAIL_CONFIG",

    79: "MSP_SDCARD_SUMMARY",

    80: "MSP_BLACKBOX_CONFIG",
    81: "MSP_SET_BLACKBOX_CONFIG",

    82: "MSP_TRANSPONDER_CONFIG",
    83: "MSP_SET_TRANSPONDER_CONFIG",

    84: "MSP_OSD_CONFIG",
    85: "MSP_SET_OSD_CONFIG",

    86: "MSP_OSD_CHAR_READ",
    87: "MSP_OSD_CHAR_WRITE",

    88: "MSP_VTX_CONFIG",
    89: "MSP_SET_VTX_CONFIG",

    90: "MSP_ADVANCED_CONFIG",
    91: "MSP_SET_ADVANCED_CONFIG",

    92: "MSP_FILTER_CONFIG",
    93: "MSP_SET_FILTER_CONFIG",

    94: "MSP_PID_ADVANCED",
    95: "MSP_SET_PID_ADVANCED",

    96: "MSP_SENSOR_CONFIG",
    97: "MSP_SET_SENSOR_CONFIG",

    98: "MSP_CAMERA_CONTROL",

    99: "MSP_SET_ARMING_DISABLED",

    180: "MSP_OSD_VIDEO_CONFIG",
    181: "MSP_SET_OSD_VIDEO_CONFIG",

    182: "MSP_DISPLAYPORT",

    183: "MSP_COPY_PROFILE",

    184: "MSP_BEEPER_CONFIG",
    185: "MSP_SET_BEEPER_CONFIG",

    186: "MSP_SET_TX_INFO",
    187: "MSP_TX_INFO",

    100: "MSP_IDENT",

    101: "MSP_STATUS",
    102: "MSP_RAW_IMU",
    103: "MSP_SERVO",
    104: "MSP_MOTOR",
    105: "MSP_RC",
    106: "MSP_RAW_GPS",
    107: "MSP_COMP_GPS",
    108: "MSP_ATTITUDE",
    109: "MSP_ALTITUDE",
    110: "MSP_ANALOG",
    111: "MSP_RC_TUNING",
    112: "MSP_PID",
    113: "MSP_BOX",
    114: "MSP_MISC",
    115: "MSP_MOTOR_PINS",
    116: "MSP_BOXNAMES",
    117: "MSP_PIDNAMES",
    118: "MSP_WP",
    119: "MSP_BOXIDS",
    120: "MSP_SERVO_CONFIGURATIONS",
    121: "MSP_NAV_STATUS",
    122: "MSP_NAV_CONFIG",

    124: "MSP_MOTOR_3D_CONFIG",
    125: "MSP_RC_DEADBAND",
    126: "MSP_SENSOR_ALIGNMENT",
    127: "MSP_LED_STRIP_MODECOLOR",
    128: "MSP_VOLTAGE_METERS",
    129: "MSP_CURRENT_METERS",
    130: "MSP_BATTERY_STATE",
    131: "MSP_MOTOR_CONFIG",
    132: "MSP_GPS_CONFIG",
    133: "MSP_COMPASS_CONFIG",
    134: "MSP_ESC_SENSOR_DATA",
    135: "MSP_GPS_RESCUE",
    136: "MSP_GPS_RESCUE_PIDS",
    137: "MSP_VTXTABLE_BAND",
    138: "MSP_VTXTABLE_POWERLEVEL",
    139: "MSP_MOTOR_TELEMETRY",

    140: "MSP_SIMPLIFIED_TUNING",
    141: "MSP_SET_SIMPLIFIED_TUNING",
    142: "MSP_CALCULATE_SIMPLIFIED_PID",
    143: "MSP_CALCULATE_SIMPLIFIED_GYRO",
    144: "MSP_CALCULATE_SIMPLIFIED_DTERM",
    145: "MSP_VALIDATE_SIMPLIFIED_TUNING",

    200: "MSP_SET_RAW_RC",
    201: "MSP_SET_RAW_GPS",
    202: "MSP_SET_PID",
    203: "MSP_SET_BOX",
    204: "MSP_SET_RC_TUNING",
    205: "MSP_ACC_CALIBRATION",
    206: "MSP_MAG_CALIBRATION",
    207: "MSP_SET_MISC",
    208: "MSP_RESET_CONF",
    209: "MSP_SET_WP",
    210: "MSP_SELECT_SETTING",
    211: "MSP_SET_HEADING",
    212: "MSP_SET_SERVO_CONFIGURATION",
    214: "MSP_SET_MOTOR",
    215: "MSP_SET_NAV_CONFIG",

    217: "MSP_SET_MOTOR_3D_CONFIG",
    218: "MSP_SET_RC_DEADBAND",
    219: "MSP_SET_RESET_CURR_PID",
    220: "MSP_SET_SENSOR_ALIGNMENT",
    221: "MSP_SET_LED_STRIP_MODECOLOR",
    222: "MSP_SET_MOTOR_CONFIG",
    223: "MSP_SET_GPS_CONFIG",
    224: "MSP_SET_COMPASS_CONFIG",
    225: "MSP_SET_GPS_RESCUE",
    226: "MSP_SET_GPS_RESCUE_PIDS",
    227: "MSP_SET_VTXTABLE_BAND",
    228: "MSP_SET_VTXTABLE_POWERLEVEL",

    240: "MSP_BIND",
    242: "MSP_ALARMS",

    250: "MSP_EEPROM_WRITE",

    251: "MSP_RESERVE_1",
    252: "MSP_RESERVE_2",
    253: "MSP_DEBUGMSG",
    254: "MSP_DEBUG",
    255: "MSP_V2_FRAME",

    # Additional commands that are not compatible with MultiWii
    150: "MSP_STATUS_EX",
    160: "MSP_UID",
    164: "MSP_GPSSVINFO",
    166: "MSP_GPSSTATISTICS",
    230: "MSP_MULTIPLE_MSP",
    238: "MSP_MODE_RANGES_EXTRA",
    240: "MSP_ACC_TRIM",
    239: "MSP_SET_ACC_TRIM",
    241: "MSP_SERVO_MIX_RULES",
    242: "MSP_SET_SERVO_MIX_RULE",
    245: "MSP_SET_PASSTHROUGH",
    246: "MSP_SET_RTC",
    247: "MSP_RTC",
    248: "MSP_SET_BOARD_INFO",
    249: "MSP_SET_SIGNATURE",
}

def MSPv1_function_get(id):
    return MSPv1_FUNC_TO_NAME.get(id, f"0x{id:02X} ??")


MSPv1_MSG_CONTENT = {
    2: [ # "MSP_FC_VARIANT",
        (-1, str),
    ],
    101: [ # "MSP_STATUS",
        (2, "PID us"),
        (2, "I2C errors"),
        (2, "Sensors mask"),
        (4, "Flight mode flags"),
        (1, "PID Profile Idx"),
        (2, "System Load Avg"),
        (2, "Gyro Cycle Time"),
        (1, "Flight Mode Byte Cnt"),
        (0, "TBD, Variable size"),
        (1, "Arming Disabled Flags Count"),
        (4, "Arming Disabled Flags"),
        (1, "Config State Flags"),
    ],
    105:  # "MSP_RC",
        [(4, f"CH{x}") for x in range(18)]
    ,
    182: [ # MSP_DISPLAYPORT
        (1, {0:"Heartbeat", 1:"release", 2:"clear", 3:"write", 4:"draw"}),
        (1, "row"),
        (1, "col"),
        (1, "attr"),
        (-1, str),
    ],
}
def MSPv1_function_content_get(func):
    return MSPv1_MSG_CONTENT.get(func, [])



MSPv2_FUNC_TO_NAME = {

}

def MSPv2_function_get(id):
    return MSPv2_FUNC_TO_NAME.get(id, f"0x{id:04X} ??")
